### PR TITLE
Azure Search implementation for BotFramework v4 C#

### PR DESCRIPTION
**Pull request by ikivanc**
Hi Team, 

Here is the Azure Search implementation for BotFramework v4 C#

If anything is help is needed I'll be happy to help.

Thanks.

### CODE REVIEW

**Comment by sgellock** [comment]
new sample that also needs to a complementary implementation in NodeJS

**Comment by daveta** [comment]
@ikivanc : Can you rebase?
Also, can you add the copyright headers on top of all the files?  I'll review after rebase.

**Comment by cleemullins** [comment]
@ikivanc I'm not quite sure what to do with this. Is this a sample we should consider integrating into our samples tree, or is this something more likley that should be in our [community hosted samples](https://github.com/botBuilderCommunity/)? 

This sample will need to be rebased against master before we can do much with it in this repo.

**Comment by ikivanc** [comment]
Hi @daveta , added copyright headers onto top of all files.

@cleemullins I would like to integrate this code into botbuilder samples, since this is a common scenario needed by many developers. Please can you check it right now?

**Comment by sgellock** [comment]
This looks like an abandoned PR.  If there is no activity on this in the next 5 days, then I'm going to close it.  I needs to be rebased before it can be reviewed and considered for a merge

**Comment by sgellock** [comment]
@ikivanc are you open to rebasing your PR?  If so, we can get it merged.

**Comment by ikivanc** [comment]
Hi @sgellock , I rebased it, is it possible to check right now?

**Comment by Expecho** [comment]
So, is this still work in progress or is it abandoned? I very welcome an example of how to integrate Azure Search.

**Comment by cleemullins** [comment]
The best place for this - and it's an awesome feature (!!) - is in the Community Repo. 
https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/samples

**Pull request closed without merging**
