### PR TITLE
feat: multiply dialog package sample

### PR DESCRIPTION
**Pull request by joshgummersall**
This is a sample package that is consumable by the new adaptive runtime.

### CODE REVIEW

**Comment by tracyboehrer** [comment]
@joshgummersall @clearab This is interesting.  I hadn't thought of doing this.  But... I have some code for DotNet that we could do exactly the same thing with.  Is this part of our samples story?

**Comment by joshgummersall** [comment]
@tracyboehrer, @sgellock mentioned that having a sample package would be useful (alongside some documentation and perhaps a Yeoman generator to handle scaffolding). I figured I would start with the sample, write some docs, and then work on a generator at some point. The sample could live somewhere else (in the components repo?).

**Comment by tracyboehrer** [comment]
No I love it.  I hadn't heard where we were putting them.  I thought the same, and have the basis of the DotNet version in Components (experimental).  Is Samples where we want these things?

**Comment by tracyboehrer** [comment]
I was in the process of trying to tell the story of:  1) How to write a custom action, 2) In the same project as the bot, 3), in a separate project but not a component, 4) as a component.

On the idea that not everyone will want to bother with a component package.

**Comment by clearab** [comment]
Talking a bit with @sgellock on this, I believe this is a great place to put this for now. @tracyboehrer do you want to do a C# port of this, or would you like me to?

**Comment by tracyboehrer** [comment]
I'll do it.  It really already there.  I'll make sure it meets our standards and match what Josh did.  There is already a standalone project with the correct stuff that allows it to be published as a component.  Tested as such as well.

**Comment by clearab** [comment]
@tracyboehrer do you think we should tell that story in a single sample? We might be able to if we made this something like:

1. A bot project that could be opened in Composer
2. Include the multiply action in a separate project
3. Add build steps to package the component project

Not sure what happens with registering the custom action. Can I use 'botComponent' in the separate file if I'm not adding as a package, or do I still need to manually wire up in startup.cs?

**Comment by tracyboehrer** [comment]
@clearab I think there could be multiple stories.  This one is how to write a custom action that is intended to be published to npm/nuget.  The story is a little harder to tell if they don't intend to publish and just want it local. In that case it's more like the old doc Composer has on adding a custom action (but slightly different).  Namely, they have to run the update-schema script and modify appsettings to include the component in runtimeSettings/components.  I did get that script working with the new RT layout (this fix is in the current generator).

I think we should lead with the easy story.  Publishing a component.  Easier to tell, and it shows people how to create new components.  Two-fer.

The easier story is:
1) Write your custom action, BotComponent, and publish it.
2) Add it to a Composer project
3) Hook it up in Composer

To not go the publish route:
1) Create a project in Composer (or use an existing one)
2) Add a custom action project to the solution and implement the custom action and BotComponent.
3) In the bot project add a dependency to the custom action.
4) Run update-schema
5) Update runtimeSettings/components in appsettings to include the custom action assembly name.

Branch https://github.com/microsoft/botframework-components/tree/trboehre/customaction has the second scenario.  It consists of EmptyBot (the Composer project, nothing special about it), and the CustomAction.  Though, that CustomAction project is setup to produce a component that could be published (I tested that by publishing to local repo).

I'd just take the CustomAction portion, clean it up, and put it in samples like Josh did.

**Review by tracyboehrer — APPROVED** [review]

**Pull request merged**
