### PR TITLE
Update 08.todo-bot-luis-qnamaker sample based on latest cross-train cli

### LINKED ISSUE #2896: Got an error running luis:crosstrain command in adaptive sample #8
#2186  Sample information
1. Sample type: \samples\ 
2. Sample language: dotnetcore 
3. Sample name: Todo bot with LUIS and QnA Maker

## Describe the bug
Error when running luis:crosstrain command, missing chitchat.qna file

## To Reproduce
1. Follow instruction on README
2. Ran the bf luis:crosstrain command

## Expected behavior
No error after bf luis:crosstrain command

## Screenshots
image

### PR DESCRIPTION
**Pull request by feich-ms**
Fixes #2896

## Proposed Changes
Updated the README and some code and config pieces based on latest cross-train cli.

## Testing
Manual tests show it is fixed and working well now.

### CODE REVIEW

**Review by tsuwandy — APPROVED** [review]

**Comment by feich-ms** [comment]
Hi @johnataylor could you help to review and approve when you are convenient?

**Comment by feich-ms** [comment]
Hi @cleemullins, could you or anyone else review this fix of the sample doc?

**Comment by tsuwandy** [comment]
@EricDahlvang, could you approve?  This sample has been broken and will be fixed with Fei’s changes.  Thanks!

**Comment by feich-ms** [comment]
@scheyal could you or anyone else help to push the approve of this PR. We have several docs depending on this sample to introduce the cross-train concept and usage.

**Review by EricDahlvang — APPROVED** [review]

**Comment by EricDahlvang** [comment]
Note: this project is scheduled to be moved to Experimental as part of this issue https://github.com/microsoft/BotBuilder-Samples/issues/2856

**Pull request merged**
