### PR TITLE
Add custom data-driven dialogs sample [POST IGNITE]

### PR DESCRIPTION
**Pull request by benbrown**
This sample creates a data-driven dialog class that reads a script from a JSON file instead of accepting a stack of functions.

### CODE REVIEW

**Comment by benbrown** [comment]
- [ ] Update readme
- [ ] Careful grammar & style review

**Comment by stevengum** [comment]
Closing per #363 (merged) and #357 (closed). @benbrown if this should be reopened, then please do so!

**Comment by benbrown** [comment]
This is actually a post-Ignite sample that is different from the custom dialog sample we landed on.

**Comment by cleemullins** [comment]
Closing this PR after a discussion with @benbrown. This may become a blog post or something similar.

**Pull request closed without merging**
