### PR TITLE
Add carousel to node card sample

### PR DESCRIPTION
**Pull request by JasonSowers**
Change is yet to be tested because of https://github.com/Microsoft/botbuilder-js/issues/643

### CODE REVIEW

**Comment by cleemullins** [comment]
@stevengum Can you verify this actually works? @JasonSowers was unable to verify due to Microsoft/botbuilder-js#643 which is now fixed.

**Comment by cleemullins** [comment]
@Zerryth Can you verify this works when you have a moment? 

(Removed @stevengum , as he's over-booked right now)

**Comment by Zerryth** [comment]
@cleemullins yeah no problem!

I'll check it out tomorrow

**Comment by Zerryth** [comment]
Carousel works! :)

**Pull request merged**
