### PR TITLE
Samples Consolidation

### LINKED ISSUE #2212: [Refine] QnA Maker samples
**UPDATE 06/11** - The new plan of record is to keep samples 11 and 14. Our documentation is aligned with these and sample 11 allows users to see a simple implementation of qna maker. The new consolidated sample should consolidate 48, 49 and 70. Sample 49 would then act as the advanced sample.

Today, we have 5 different samples that cover [QnA Maker][1] concepts - 
- 11.qnamaker - [C#][C1] [JS][J1]
- 14.nlp-with-dispatch - [C#][C2] [JS][J2]
- 48.qnamaker-active-learning-bot - [C#][C3] [JS][J3]
- 49.qnamaker-all-features - [C#][C4] [JS][J4]
- 70.qnamaker-multiturn-sample - [C#][C5] [JS][J5]

We should refine and consolidate this list to the following reduced set of samples that streamline the covered concepts and is representative of typical customer workflow needs. 

| Sample | Keep/ Remove | Comments |
|---------|---------------|-------------|
| 11.qnamaker | keep | Shows simple bot with only qna maker integration and no other cognitive service. We should have this sample be the template for ABS (create bot from QnA KB flow) and so it should **support all QnA Maker concepts including multi-turn and active learning.** |
| 14.nlp-with-dispatch | keep | This is the only sample that shows dispatching across LUIS and QnA Maker. We will keep this but need to **update this to show dispatching with qna multi-turn** |
| ~48.qnamaker-active-learning-bot~ | **remove** | Covered via 11.qnamaker |
| ~49.qnamaker-all-features~ | **remove** | Covered via 11.qnamaker |
| ~70.qnamaker-multiturn-sample~ | **remove** | Covered via 11.qnamaker |

[1]:https://qnamaker.ai
[C1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker
[J1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker
[C2]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch
[J2]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/14.nlp-with-dispatch
[C3]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/48.qnamaker-active-learning-bot
[J3]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/48.qnamaker-active-learning-bot
[C4]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/49.qnamaker-all-features
[J4]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/49.qnamaker-all-features
[C5]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/70.qnamaker-multiturn-sample
[J5]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/70.qnamaker-multiturn-sample

### PR DESCRIPTION
**Pull request by vipeketi**
Fixes #2212 

## Proposed Changes
We should refine and consolidate this list to the following reduced set of samples that streamline the covered concepts and is representative of typical customer workflow needs. Sample 49 is all feature sample. It is renamed as 11 now. Sample 48 70 are excluded .no
  - 
  -
  -

### CODE REVIEW

**Comment by vipeketi** [comment]
@vishwacsena please suggest.

> We have documentation that refers to sample 11 as it is.
> 
> https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs
> 
> We'd need to update that alone with any changes we make here. **So don't merge for now.**

@vishwacsena  Please suggest.

**Comment by vishwacsena** [comment]
@Kaiqb what changes if any are required to the current doc? https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs

@johnataylor Apart from the basics of getting set up with QnA Maker KB, I do not see much in the doc which should not bear any impact due to this sample. Can you clarify what changes do we need to make to this PR to address any concerns?

**Comment by johnataylor** [comment]
Sorry accidently closed. We do want this PR in principle. We do feel the QnAMaker samples could be consolidated and that would make the feature more approachable and easier to learn.

However, the docs currently refer to code verbatium, for exampe the code [here]( https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=cs#calling-qna-maker-from-your-bot) that shows code that would be deleted by these changes as far as I understand it.

Specifically the docs show adding a GetAnswersAsync call inline in the QnABot OnMessageActivityAsync code - this is a reference to the current sample 11. However the new code replaces this with a call to run the dialogs.

So this PR would make the docs and the sample out of sync.

There are a bunch of alternatives here: for example update the docs. Or we could decide that we think the super basic sample 11 is good and we like the docs and so we consolidate only the more advanced samples into a single sample. Ending out with two samples: basic and advanced.

**Comment by garypretty** [comment]
@vipeketi Can you resolve the conflicts in this PR and also update to leave sample 11 unchanged, just consolidating samples 48 / 70 into 49.
Thanks

**Comment by vipeketi** [comment]
Abandoning this PR for changes moved to simple delete task,  fresh PR https://github.com/microsoft/BotBuilder-Samples/pull/2494.

**Pull request closed without merging**
