### PR TITLE
[Do not merge] Update sample to be tool first .

### PR DESCRIPTION
**Pull request by chrimc62**
This makes sample 13 msbot clone and be tools first.  Please review the readme and if it works we can follow a similar pattern for other samples with services.

Note that I renamed BotConfiguration.bot to be sample specific--that way if you have multiple samples in the emulator you can distinguish between them.

### CODE REVIEW

**Comment by vishwacsena** [comment]
@chrimc62 - I like this approach a lot. I'll update all samples that use LUIS to this model. Really good set of readme updates.

**Comment by vishwacsena** [comment]
Also not merging in since this has impact on VSIX, ABS as well as Yeoman on the node side. The right fix for now is to update samples with this model and look to fix VSIX, Yeoman and ABS next week. 

@sgellock as FYI

**Comment by cleemullins** [comment]
@daveta, @vishwacsena, @chrimc62 Is this something to "hold" until after Ignite? 

The implications here are across all the samples, ABS, VSIX and Yeoman - all of which are locked at this point.

**Comment by sgellock** [comment]
Can I get the TL;DR of what needs to change in the samples, visix and yeoman templates?



On Sep 23, 2018, at 9:45 AM, Chris Mullins <notifications@github.com<mailto:notifications@github.com>> wrote:


@daveta<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaveta&data=02%7C01%7Cscott.gellock%40microsoft.com%7Cb539fddcf9f14b2f9bcc08d621740219%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636733179469880850&sdata=aGXxK%2BkupJbcefJfTC7ceR5jdiaB%2BExBdnqavWZu3iI%3D&reserved=0>, @vishwacsena<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvishwacsena&data=02%7C01%7Cscott.gellock%40microsoft.com%7Cb539fddcf9f14b2f9bcc08d621740219%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636733179469890850&sdata=Q6D9ILIWAW8EjoNnZ802mEzdw9pjTw5yahtn2sCtgOo%3D&reserved=0>, @chrimc62<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrimc62&data=02%7C01%7Cscott.gellock%40microsoft.com%7Cb539fddcf9f14b2f9bcc08d621740219%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636733179469900863&sdata=IjnWDLbWoOXSOd61Rn6%2FZlQHklU9WmGeoU%2FRGtRxtms%3D&reserved=0> Is this something to "hold" until after Ignite?

The implications here are across all the samples, ABS, VSIX and Yeoman - all of which are locked at this point.

**Pull request closed without merging**
