### PR TITLE
[LUIS Action Binding] Updates

### PR DESCRIPTION
**Pull request by pcostantini**
- LUIS Model and how to upload model
- [NodeJS] NPM Package - bug & repository properties
- [NodeJS] README - Info on missing `evaluate()` parameters
- [NodeJS] Code Cleanup

### CODE REVIEW

**Comment by ejadib** [comment]
@RobStand @matthewshim-ms FYI

**Comment by cleemullins** [comment]
Looks good to me. I'll wait for Robert / Matt to merge though as I've got no context.

**Comment by ejadib** [comment]
@RobStand / @matthewshim-ms since the blog post is already public, we should merge this as soon as possible.

**Comment by cleemullins** [comment]
Hi Mat – can you confirm you can merge this ASAP?

**Pull request merged**
