### PR TITLE
DO NOT MERGE Update bot.recipe

### LINKED ISSUE #692: [netcore][20.qna-with-appinsights] bot.recipe without QnA spec
## Sample information
1. Sample type: **samples**
2. Sample language: **dotnetcore**
3. Sample name: **20.qna-with-appinsights**

## Describe the bug
The [`bot.recipe`](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/20.qna-with-appinsights/DeploymentScripts/MsBotClone/bot.recipe) used does not have contain a QnA service to deploy.

## To Reproduce
1. Follow the ["Deploy this bot to Azure"](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/20.qna-with-appinsights#deploy-this-bot-to-azure) instructions.
2. Run `msbot clone services -f deploymentScripts/msbotClone -n mybot -l westus`.
3. The `msbot` does not list any `QnA` service.

## Expected behavior
The `msbot` script should install all required services.

## Screenshots
image

[bug]

### PR DESCRIPTION
**Pull request by JasonSowers**
add qna to .recipe file

Fixes #692

### CODE REVIEW

**Comment by JasonSowers** [comment]
I think I am missing something, there is not a file named `34.qna` involved in this at all.  Is there a reference to it somewhere?

**Comment by enzocanoo** [comment]
The modified file has an `id` that is used to link the `.qna` file needed to allocate the QnA service resources.
If you use `msbot clone services` with the current file, it will fail because the QnA service needs to add the resources to work with.

You can use the TypeScript sample [52.enterprise-bot](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_typescript/52.enterprise-bot/deploymentScripts/msbotClone) as an example. The `bot.recipe` contains the following definition for QnA service:
```json
    {
      "type": "qna",
      "id": "85",
      "name": "FAQ"
    },
```
And the directory contains a file called `85.qna` with the QnA resources for that sample.

**Comment by JasonSowers** [comment]
Got it, thanks!

**Comment by JasonSowers** [comment]
Remaking pr my branch got messed up 👎

**Pull request closed without merging**
