### PR TITLE
Sample for App Insights integration

### PR DESCRIPTION
**Pull request by brandonh-msft**
This BotBuilder Sample provides guidance on how to implement Application Insights throughout your bot in a way that enables data-driven decisions on bot evolution and feature/bug prioritization.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brandonh-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@brandonh-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by brandonh-msft** [comment]
FWIW I'm still trying to get some answers as to why AZPRBOT isn't whitelisting me as an FTE.

**Comment by azurecla** [comment]
Hi __@brandonh-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hurlburb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Pull request merged**
