### PR TITLE
Adding new sample to demo authentication in Messaging Extension action.

### PR DESCRIPTION
**Pull request by Wajeed-msft**
Adding new sample to demo authentication in Messaging Extension action. This sample code uses this fix - https://github.com/microsoft/botbuilder-dotnet/issues/4709.

## Proposed Changes
Adding new sample code to demo authentication for [Messaging Extension action command](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command). 

**Screenshots of the code in action:**
Request for Auth:
image
Showing Display Name:
image

### CODE REVIEW

**Comment by clearab** [comment]
If this gets merged, please create an Issue and add to the Teams board to prioritize porting to other languages and moving from experimental folder.

**Comment by EricDahlvang** [comment]
Sorry it is not clear to me, how does this differ from what is demonstrated in:
 https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config ?

**Comment by clearab** [comment]
This one initiates the auth flow from an action command, rather than a search command. Probably makes sense to merge the two?

**Comment by Wajeed-msft** [comment]
Closing this as we are raising separate PR with changes including common auth sample.

**Pull request closed without merging**
