### PR TITLE
Add missing DEPLOYMENT.md file

### LINKED ISSUE #779: javascript_nodejs/09.message-routing/ README has a broken link
## Sample information
1. Sample type: \samples\ 
2. Sample language: nodejs
3. Sample name: 09.message-routing

## Describe the bug
Link in the section ["To try this sample"](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/09.message-routing#to-try-this-sample) is broken. "Required services" goes to a GitHub 404 page.

## To Reproduce
1. Go to https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/09.message-routing#to-try-this-sample
2. Scroll down to ["To try this sample"](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/09.message-routing#to-try-this-sample). Click link in the fourth bullet ("Create required services")
image

4. get 404 error.
image

[bug]

### PR DESCRIPTION
**Pull request by maixiu**
Fixes #779

## Proposed Changes
Added deploymentScripts/DEPLOYMENT.md file to which the README.md is linked.

### CODE REVIEW

**Comment by joseques** [comment]
Hi @maixiu 
Thank you for your contribution but this has been fixed in #787 
Since the sample doesn't use any services like LUIS, deploying it isn't mandatory, hence the step `Create required services` has been removed.

**Comment by cleemullins** [comment]
@joseques I believe we should close out this PR as a dupe (mostly) of #787. Thoughts?

**Comment by joseques** [comment]
Hi @cleemullins 
Yes, indeed this PR is a duplicate of #787 and should be closed!

**Comment by maixiu** [comment]
Ok understood, I close this PR

**Pull request closed without merging**
