### PR TITLE
Handoffv2

### PR DESCRIPTION
**Pull request by arturl**
This set of changes implements feedback from today's design review

### CODE REVIEW

**Comment by EricDahlvang** [comment]
I see this removes the Transcript. As a developer, user or agent: some transcript option seems integral to a proper Handoff scenario.  Is that work planned for a future iteration? (curious)

**Comment by arturl** [comment]
> I see this removes the Transcript. As a developer, user or agent: some transcript option seems integral to a proper Handoff scenario. Is that work planned for a future iteration? (curious)

@EricDahlvang, Transcript is not removed. See [here](https://github.com/microsoft/BotBuilder-Samples/tree/handoffv2/experimental/handoff-library#attachments).

**Comment by EricDahlvang** [comment]
Oh, i see. Thanks. 

Are there plans to add paged transcript support to this api? Or is the expectation that the entire transcript is sent at the handoff initiation?

**Comment by carlosscastro** [comment]
Great point @EricDahlvang on transcripts / attachments. We are having some discussions on that, I'll chat iwht you about that in person and get your thoughts :)

**Comment by arturl** [comment]
@EricDahlvang, @carlosscastro - if the agent hub supports it, the bot can send transcript in "offline" attachments using the ContentUrl property. The protocol does not prohibit other schemes.

**Pull request merged**
