### PR TITLE
Fix missing default.htm and accommodate any underscores in bot name

### LINKED ISSUE #557: NLP with Dispatch throws exception after following readme instructions
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore
3. Sample name: 14.nlp-with-dispatch

## Describe the bug
Follow README instructions up through **Securing keys in your .bot file** and [**Visual Studio**](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch#visual-studio). The bot throws an exception during setup.

## To Reproduce
1. Follow the instructions in the readme. (Use your own subscription key instead of the hard coded one for QnA Maker. Update your **appsettings.json** file instead of the **.env** file for recording your secret key.)
1. Open the project in Visual Studio and hit F5.
1. A web page is displayed, with an exception (see screenshot).

## Expected behavior
The bot should run.

## Screenshots
capture

[bug]

### PR DESCRIPTION
**Pull request by daveta**
Fixes #557 

@JonathanFingold  found missing default.htm file, and modified LUIS/Dispatch name demangling to handle bot names with underscores.

### CODE REVIEW

**Comment by JonathanFingold** [comment]
@JasonSowers Thanks. Any chance you can address the endpoint name issue in the .bot file and the `dispatch.SubscriptionKey` issue in the Startup.cs file? The Dispatch subscription key issue might be a bug in the readme instructions or in the msbot or dispatch CLI tool.

**Comment by JonathanFingold** [comment]
@JasonSowers I'm not entirely sure why this is needed, but if you follow the thread on the issue, someone else said that one of the tools prepends the bot name, plus an underscore, to the LUIS and dispatch app names. I didn't see it in my .bot file, though.

That said, there are two lines that have the issue, the one you found for dispatch, and another one for luis services.

The [fragile] fix appears to be `.Split("_").Last()`, as you have it above. This feels fragile, since someone could unwittingly include an underscore in one of their app names and break this.

**Comment by daveta** [comment]
@JonathanFingold : Can you post two things:

- The command line (remove the LUIS authoring key!) of your msbot command line.
- The resulting .bot configuration file (removing all keys)

I'm presuming you are naming your bot with a space in it, and I presume you don't have a subscription key?  The authoring key can be used in place of the subscription key.  The catch is you only get a certain number of calls with the authoring key.

Thanks.

**Comment by JonathanFingold** [comment]
@daveta Here you go:
- I'm really am just following the lines as they appear in the readme, with the exception of running `qna init` and `luis init` first:
```shell
ludown parse toluis --in Resources/homeautomation.lu -o CognitiveModels --out homeAutomation.luis -n "Home Automation" -d "Home Automation LUIS application - Bot Builder Samples" --verbose
ludown parse toluis --in Resources/weather.lu -o CognitiveModels --out weather.luis -n Weather -d "Weather LUIS application - Bot Builder Samples" --verbose
luis import application --in CognitiveModels/homeAutomation.luis --authoringKey <LUIS-AUTHORING-KEY> --region <LUIS-AUTHORING-REGION> --msbot | msbot connect luis --stdin
luis import application --in CognitiveModels/weather.luis --authoringKey <LUIS-AUTHORING-KEY> --region <LUIS-AUTHORING-REGION> --msbot | msbot connect luis --stdin

msbot get "Home Automation" | luis train version --wait --stdin
msbot get "Weather" | luis train version --stdin --wait
msbot get "Home Automation" | luis publish version --stdin
msbot get "Weather" | luis publish version --stdin

ludown parse toqna --in resources/sample-qna.lu -o cognitiveModels --out dispatch.qna --verbose
qnamaker create kb --in cognitiveModels/dispatch.qna --subscriptionKey <QNA-MAKER-SUBSCRIPTION-KEY> --msbot | msbot connect qna --stdin

msbot get "sample-qna" | qnamaker publish kb --stdin

dispatch create -b BotConfiguration.bot | msbot connect dispatch --stdin

msbot secret -n
```
- And here is the resulting bot file:
```json
{
    "name": "NLP-With-Dispatch-Bot",
    "description": "",
    "services": [
        {
            "type": "endpoint",
            "name": "<some-name-other-than-development>",
            "id": "http://localhost:3978/api/messages",
            "appId": "",
            "appPassword": "",
            "endpoint": "http://localhost:3978/api/messages"
        },
        {
            "type": "luis",
            "name": "Home Automation",
            "appId": "ef40dce4-611d-40d8-9bee-374d6b3c31f0",
            "version": "0.1",
            "authoringKey": "<encrypted-stuff>",
            "subscriptionKey": "<encrypted-stuff>",
            "region": "westus",
            "id": "162"
        },
        {
            "type": "luis",
            "name": "Weather",
            "appId": "29e24ac7-30fb-4fd4-9e6e-e1ee1a96afe1",
            "version": "0.1",
            "authoringKey": "<encrypted-stuff>",
            "subscriptionKey": "<encrypted-stuff>",
            "region": "westus",
            "id": "14"
        },
        {
            "type": "qna",
            "name": "sample-qna",
            "kbId": "1ee7c8e6-0d18-4bf5-a8a0-6d4d5eed8caf",
            "subscriptionKey": "<encrypted-stuff>",
            "endpointKey": "<encrypted-stuff>",
            "hostname": "https://jf-qnamaker.azurewebsites.net/qnamaker",
            "id": "49"
        },
        {
            "type": "dispatch",
            "name": "NLP-With-Dispatch-BotDispatch",
            "appId": "f5e0ee97-d054-4a17-935b-69f394fea517",
            "authoringKey": "<encrypted-stuff>",
            "version": "Dispatch",
            "region": "westus",
            "serviceIds": [
                "162",
                "14",
                "49"
            ],
            "id": "236"
        }
    ],
    "padlock": "<encrypted-stuff>",
    "version": "2.0"
}
```

Also, I'm just using the same name as sample 14 uses, `NLP-With-Dispatch-Bot`.

**Pull request merged**
