### PR TITLE
Fixes #2212 [QnAMaker] [Samples consolidation] Deleting 48 and 70

### LINKED ISSUE #2212: [Refine] QnA Maker samples
**UPDATE 06/11** - The new plan of record is to keep samples 11 and 14. Our documentation is aligned with these and sample 11 allows users to see a simple implementation of qna maker. The new consolidated sample should consolidate 48, 49 and 70. Sample 49 would then act as the advanced sample.

Today, we have 5 different samples that cover [QnA Maker][1] concepts - 
- 11.qnamaker - [C#][C1] [JS][J1]
- 14.nlp-with-dispatch - [C#][C2] [JS][J2]
- 48.qnamaker-active-learning-bot - [C#][C3] [JS][J3]
- 49.qnamaker-all-features - [C#][C4] [JS][J4]
- 70.qnamaker-multiturn-sample - [C#][C5] [JS][J5]

We should refine and consolidate this list to the following reduced set of samples that streamline the covered concepts and is representative of typical customer workflow needs. 

| Sample | Keep/ Remove | Comments |
|---------|---------------|-------------|
| 11.qnamaker | keep | Shows simple bot with only qna maker integration and no other cognitive service. We should have this sample be the template for ABS (create bot from QnA KB flow) and so it should **support all QnA Maker concepts including multi-turn and active learning.** |
| 14.nlp-with-dispatch | keep | This is the only sample that shows dispatching across LUIS and QnA Maker. We will keep this but need to **update this to show dispatching with qna multi-turn** |
| ~48.qnamaker-active-learning-bot~ | **remove** | Covered via 11.qnamaker |
| ~49.qnamaker-all-features~ | **remove** | Covered via 11.qnamaker |
| ~70.qnamaker-multiturn-sample~ | **remove** | Covered via 11.qnamaker |

[1]:https://qnamaker.ai
[C1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/11.qnamaker
[J1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker
[C2]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch
[J2]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/14.nlp-with-dispatch
[C3]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/48.qnamaker-active-learning-bot
[J3]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/48.qnamaker-active-learning-bot
[C4]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/49.qnamaker-all-features
[J4]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/49.qnamaker-all-features
[C5]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/70.qnamaker-multiturn-sample
[J5]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/70.qnamaker-multiturn-sample

### PR DESCRIPTION
**Pull request by vipeketi**
Fixes #2212

## Proposed Changes
Samples consolidation changes include 48 and 70 examples deletion.
Update Readme files at project level and 49 level.

### CODE REVIEW

**Comment by garypretty** [comment]
Hi @vipeketi.  We have been reviewing samples / docs as part of our R10 planning and we have landed on an approach for QnA Maker samples.  The new plan of record is to *keep*  samples 11 and 14.  Our documentation is aligned with these and sample 11 allows users to see a simple implementation of qna maker.

The new consolidated sample should consolidate 48, 49 and 70. Sample 49 would then act as the advanced sample.

I *believe* that this PR does the consolidation of 48, 49 and 70 into a single sample (49) - can you confirm?
If that is the case then once this PR has been reviewed and merged, this should meet our intended end state.

cc @vishwacsena @johnataylor @Kaiqb

**Comment by vipeketi** [comment]
@garypretty    Yes. This PR is consolidation of 48, 49 and 70 to 49.

**Comment by vipeketi** [comment]
@vishwacsena The changes are just deletion for 48.ActiveLearning and 70.Multiturn, for C# and nodejs. There are no more merging changes. (48.ActiveLearning and 70.MultiTurn, which features are already available in 49). Please Review.

**Comment by vishwacsena** [comment]
@vipeketi can you update to resolve conflicts? This looks good to me. @johnataylor @garypretty is this good to go from your end as well?

**Comment by vipeketi** [comment]
> @vipeketi can you update to resolve conflicts? This looks good to me. @johnataylor @garypretty is this good to go from your end as well?

Done!

**Comment by vipeketi** [comment]
@Vishwac Sena Kannan , conflicts are resolved now.

---
In reply to: [648259309](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-648259309) [](ancestors = 648259309)

**Comment by vipeketi** [comment]
@Gary Pretty    Yes. This PR is consolidation of 48, 49 and 70 to 49.

---
In reply to: [642618053](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-642618053) [](ancestors = 642618053)

**Comment by johnataylor** [comment]
So this PR deletes 48 and 70.

Isn't the idea to incorporate what 48 and 70 have into 49?

(And leave 11 alone.)

Because if that is the case I would have expected the updates to 49 in the same PR, if this is basically moving code around. Or are you saying 48 and 70 are just redundant and can go?

**Comment by garypretty** [comment]
In addition to @johnataylor comments above - if we are just removing the redundant samples, that's fine, but I would like to see us add some steps to 49's readme to advise the user how they can use the sample to see / use each feature. e.g. "You can say ABC and this will show XYZ".  We are doing a broader review of our samples to add this level of detail, so it would be good to see this added here - especially given that this sample covers all areas, it would be good to see a list of them an how a user can try each one.

**Comment by vipeketi** [comment]
Sample 49.qnamaker-all-features,  is redundant. Hence 48 and 70 can go, without any changes/merges to 49.

---
In reply to: [648934338](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-648934338) [](ancestors = 648934338)

**Comment by vipeketi** [comment]
@garypretty,  Myself and @diberry  are having a conversation on Readme file changes, since few days.  The file is getting enhanced and would resolve the comments in this context. 
@diberry , would you like to share the track item PR/issue for the  work you are doing?
@nerajput1607 @pchoudhari , FYI. 

---
In reply to: [648937090](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-648937090) [](ancestors = 648937090)

**Comment by garypretty** [comment]
@vipeketi thanks for the comments about the sample readme.  As you say, please provide a link to a tracking issue for this.

Also, please update the readme in this PR to reflect the removal of the two samples.

Once we have the readme update in here and the link to the readme update issue, then I think this is good to be merged.  Thanks.

**Comment by vipeketi** [comment]
Worked on the README.md comment.

---
In reply to: [436829195](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-436829195) [](ancestors = 436829195)

**Comment by vipeketi** [comment]
I could update Readme files at project level and samples level for 49. 

---
In reply to: [649457267](https://github.com/microsoft/BotBuilder-Samples/pull/2494#issuecomment-649457267) [](ancestors = 649457267)

**Comment by garypretty** [comment]
@vipeketi @vishwacsena Thanks for your efforts on this. Now merged.

**Pull request merged**
