### PR TITLE
Add Blog-AdaptiveCardWeatherBot

### PR DESCRIPTION
**Pull request by EricDahlvang**

### CODE REVIEW

**Comment by EricDahlvang** [comment]
If msftclas determined that I do not need to sign a CLA, why did it also add the cla-required label?

**Comment by ejadib** [comment]
@EricDahlvang close an reopen the PR to see if that re-triggers the bot

**Comment by EricDahlvang** [comment]
@ejadib Same thing: 'cla-required', immediately following "You do not need to sign a CLA" message.

**Comment by ejadib** [comment]
@EricDahlvang recently @matthewshim-ms had the same issue and the conclusion was that the bot got confused and in fact he needed to sign the cla. Go to cla.microsoft.com, log in with your GitHub account and follow the steps

**Comment by EricDahlvang** [comment]
Closing this until complete Bot Builder Sample requirements are met.

**Pull request closed without merging**
