### PR TITLE
Add fileExists check to all dotnet samples

### PR DESCRIPTION
**Pull request by nyxsys**
Fixes https://github.com/Microsoft/BotBuilder-Samples/issues/730

## Proposed Changes
Apply the change from previous PR https://github.com/Microsoft/BotBuilder-Samples/pull/765 to the other dotnet samples that include a bot file.

## Testing
Built and ran the samples this change was applied to.

### CODE REVIEW

**Comment by cleemullins** [comment]
@Oh! A failed build. I don't know if that's awesome or terrible! On the plus side, it means we have a build hooked up with CI!! On the downside, it means it doesn't build.

**Comment by godsanchez** [comment]
Looks like most of the errors come from not adding 

`using System.IO;`

to any source file using the File class.

The rest of the errors are build issues I'm already working on.

I can disable CI for the time being, or quickly submit a fix (I'm almost done).

**Comment by godsanchez** [comment]
Fixed missing references - now currently working to finish up remaining build errors.

**Comment by godsanchez** [comment]
Build and source now updated, closed and re-opened pull request to re-trigger build, which now runs successfully.

**Pull request merged**
