### PR TITLE
[updated] [Sample 27][C#] Event Hub logger for transcript

### PR DESCRIPTION
**Pull request by congysu**
updated with core bot design style, and targeted to samples-work-in-progress branch:
* custom telemetry processor for transcript activities events.
* Event Hub batch sender for a background hosted service in asp.net core.
* use sdk version 4.3.2 - .netcore constructor-based dependency injection for appsettings, Application Insights, Event Hub, and ASP.NET Core hosted services.

This sample logs transcript activity events to Event Hub.  It creates an Application Insights custom telemetry processor, enqueues the transcript activities to an in-memory queue. The sample also constructs a background hosted service for ASP.NET Core, which dequeues transcript activities from the queue, batches activities until reaching batch size limit or configured maximum batch sending delay.  The background hosted service sends the batch when it reaches the max event batch size, or its oldest event has been in the batch for more than max batch delay seconds.

### CODE REVIEW

**Comment by congysu** [comment]
@daveta is added to the review. #Closed

**Comment by congysu** [comment]
@daveta is added to the review. #Closed

**Comment by congysu** [comment]
@cleemullins is added to the review. #Closed

**Comment by daveta** [comment]
Spoke with @cleemullins : He would like to push into @johnataylor branch (`samples-work-in-progress`), and adopt latest samples in that repo as a base for this new sample.

**Comment by benbrown** [comment]
Can you close this PR and re-open it as a DRAFT PR please?

**Comment by daveta** [comment]
@congysu : Here are my observations:
- I denormalized channel and message type (in addition to the normal activity).  If we did that, we could light up common guidance for doing PowerBI integration:
  https://github.com/daveta/analytics/tree/master/event_hubs
- (Low Pri) For nodejs, i'm using Corebot as the basis.

Let's chat today and we can sync up - I really like the approach, if we can land on common schema then I can modify for parity in nodejs and light up the Stream Analytics/Power BI stuff.

**Comment by congysu** [comment]
Thanks @daveta : The analytics and PowerBI look great.

**Comment by cleemullins** [comment]
@congysu I'm not sure what to do with this. The branch doesn't exist any more...

**Pull request closed without merging**
