### PR TITLE
Final pass updates samples 1-5 dotnetcore

### PR DESCRIPTION
**Pull request by JasonSowers**
- updated samples 1, 2, 3, 4, 5
- updated all bot files

### CODE REVIEW

**Comment by JasonSowers** [comment]
going to open a new one, it's not picking up the new f5 pages for some reason

**Comment by vishwacsena** [comment]
Jason, this is awesome progress! can you break these apart into separate PR's?

For sure we should look to lock down the echo bot sample since that has down stream dependencies with ABS, Vsix etc. 

@daveta as FYI.

**Comment by JasonSowers** [comment]
I can. I'll do it in the morning

**Comment by JasonSowers** [comment]
I lied I'll do it now...

**Comment by vishwacsena** [comment]
Jason, tomorrow is fine. Please get some rest.

**Pull request closed without merging**
